#!/usr/bin/env python3
# Made by CLOVER-6 - SQLi#9026 on discord :)

import argparse
import requests
import os

# adding and parsing of arguments
parser = argparse.ArgumentParser(
    description="An easy way to access your ngrok subdomain via PasteBin",
    prog="pastegrok",
)

parser.add_argument(
    "time",
    help="""when your post should expire | N(ever) 10M(inutes) 1H(our) 1D(ay)
                         1W(eek) 2W(eeks) 1M(onth) 6M(onths) 1Y(ear) | Default = 1W(eek)""",
    nargs="?",
    default="1W",
)

parser.add_argument(
    "privacy",
    help="""how private you want your ngrok tunnel to be (IMPORTANT: PRIVATE RECOMMENDED) | 0 = Public
                        1 = Unlisted 2 = Private | Default = 2""",
    nargs="?",
    default="2",
)

parseArgs = parser.parse_args()

# retrieving the environment variables of dev key and user key
userDevKey = os.environ["PASTEBIN_API_DEV_KEY"]
userUserKey = os.environ["PASTEBIN_API_USER_KEY"]

# requesting and receiving all running ngrok tunnels
with requests.get("http://127.0.0.1:4040/api/tunnels") as ngrokTunnels:
    ngrokContent = ngrokTunnels.content

# new user-agent in case of blocking
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "Content-Type": "application/x-www-form-urlencoded",
}

# inserting content and setting time till expiration + privacy
userAPIdata = {
    "api_dev_key": userDevKey,
    "api_paste_code": ngrokContent,
    "api_option": "paste",
    "api_user_key": userUserKey,
    "api_paste_expire_date": parseArgs.time,
    "api_paste_private": parseArgs.privacy,
    "api_paste_name": "ngrok-tunnels",
    "api_paste_format": "json",
}


# posting ngrok tunnel(s) to pastebin account
pastebinPostRequest = requests.post(
    "https://pastebin.com/api/api_post.php", headers=headers, data=userAPIdata
)
pastebinResponse = pastebinPostRequest.content.decode("utf-8")

# throwing more concise error in case of API error
if "Bad API request" not in pastebinResponse:
    # printing pastebin link
    print(
        f"""Your paste is at:
  {pastebinResponse}"""
    )
else:
    print(
        f"""A request error occurred, this could be to do with your username/password syntax (see README.md notes) or external problems

  {pastebinResponse}"""
    )
