#!/usr/bin/python3
# Made by CLOVER-6 - SQLi#9026 on discord :)

import requests
import sys

time = sys.argv[1] 

if not len(sys.argv) == 1:
    print("""Usage: pastegrok [time]
             
             time    -    when your post should expire | N(ever), 10M(inutes), 1H(our), 1D(ay),
                          1W(eek), 2W(eeks), 1M(onth), 6M(onths), 1Y(ear)""")
    
# requesting and receiving all running ngrok tunnels
with requests.get("http://127.0.0.1:4040/api/tunnels") as ngrok_tunnels:
    ngrok_content = ngrok_tunnels.content

# new user-agent in case of blocking
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36',
    'Content-Type': 'application/x-www-form-urlencoded'
}

# setting funny names lol :)
# + making all posts private (for security) and setting time till expiration 
if b"""proto":"tcp""" in ngrok_content:
    data = {
        "api_dev_key": "<DEVKEY>",
        "api_paste_code": ngrok_content,
        "api_option": "paste",
        "api_user_key": "<USERKEY>",
        "api_paste_expire_date": time,
        "api_paste_private": "2",
        "api_paste_name":"udp, but dogshit ;)",
        "api_paste_format":"JSON"
    }
elif b"""proto":"http""" in ngrok_tunnels.content:
    data = {
        "api_dev_key": "<DEVKEY>",
        "api_paste_code": ngrok_content,
        "api_option": "paste",
        "api_user_key": "<USERKEY>",
        "api_paste_expire_date": time,
        "api_paste_private": "2",
        "api_paste_name": "hatettp",
        "api_paste_format": "JSON"
    }
else:
    data = {
        "api_dev_key": "<DEVKEY>",
        "api_paste_code": ngrok_content,
        "api_option": "paste",
        "api_user_key": "<USERKEY>",
        "api_paste_expire_date": time,
        "api_paste_private": "2",
        "api_paste_name": "gettin-creative",
        "api_paste_format": "JSON"
    }

# posting ngrok tunnel(s) to pastebin account
pageget = requests.post("https://pastebin.com/api/api_post.php", headers=headers, data=data)

# printing pastebin link
print(pageget.content)
