#!/usr/bin/env python3
# Made by CLOVER-6 - SQLi#9026 on discord :)

import argparse
import requests

# parsing time arg (sys.argv is a pain in the bollocks for me)
parser = argparse.ArgumentParser(
    description="An easy way to access your ngrok subdomain via PasteBin",
    prog="pastegrok",
)

parser.add_argument(
    "time",
    help="""when your post should expire | N(ever), 10M(inutes), 1H(our), 1D(ay),
                         1W(eek), 2W(eeks), 1M(onth), 6M(onths), 1Y(ear) | Default = 1W(eek)""",
)

parse_args = parser.parse_args()

# requesting and receiving all running ngrok tunnels
with requests.get("http://127.0.0.1:4040/api/tunnels") as ngrok_tunnels:
    ngrok_content = ngrok_tunnels.content

# new user-agent in case of blocking
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
    "Content-Type": "application/x-www-form-urlencoded",
}

# setting funny names lol :)
# + making all posts private (for security) and setting time till expiration
if b"""proto":"tcp""" in ngrok_content:
    data = {
        "api_dev_key": "<DEVKEY>",
        "api_paste_code": ngrok_content,
        "api_option": "paste",
        "api_user_key": "<USERKEY>",
        "api_paste_expire_date": parse_args.time,
        "api_paste_private": "2",
        "api_paste_name": "udp, but trash ;)",
        "api_paste_format": "json",
    }
elif b"""proto":"http""" in ngrok_tunnels.content:
    data = {
        "api_dev_key": "<DEVKEY>",
        "api_paste_code": ngrok_content,
        "api_option": "paste",
        "api_user_key": "<USERKEY>",
        "api_paste_expire_date": parse_args.time,
        "api_paste_private": "2",
        "api_paste_name": "hatettp",
        "api_paste_format": "json",
    }
else:
    data = {
        "api_dev_key": "<DEVKEY>",
        "api_paste_code": ngrok_content,
        "api_option": "paste",
        "api_user_key": "<USERKEY>",
        "api_paste_expire_date": parse_args.time,
        "api_paste_private": "2",
        "api_paste_name": "gettin-creative",
        "api_paste_format": "json",
    }

# posting ngrok tunnel(s) to pastebin account
pageget = requests.post(
    "https://pastebin.com/api/api_post.php", headers=headers, data=data
)
response = pageget.content.decode("utf-8")

# throwing more concise error in case of API error
if "Bad API request" not in response:
    # printing pastebin link
    print(
        f"""Your paste is at:
  {response}"""
    )
else:
    print(
        f"""A request error occurred, this could be to do with your username/password syntax (see README.md notes) or external problems

  {response}"""
    )
